### ISSUE TITLE
Deploy blog as static web app on Azure

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/ai#16]
### Description

Tried hosting blog articles on the Github wiki space included in our subscription, but it doesn't provide basic functionality such as ordering by blog post date or displaying posts in a navigation component.

Easiest option is to use a default blog theme for a static site generator such as Astro.

### Tasks

```[tasklist]
## Tasks
- [x] Install Azure Static Web Sites extension for VS Code
- [x] Login to Azure
- [x] Use wizard to deploy new static site, Github action added to repo automatically
- [x] Adjust nodejs engine version
```

**Comment by bdb-dd** [comment]
Time spent:
- transfer content: 15 minutes
- generate article images using Dall-E 3: 5 minutes
- create dedicated repository: 5 minutes
- publish static site to Azure: 10 minutes

**Comment by bdb-dd** [comment]
Temporary blog site address: https://mango-sand-0c39e9803.4.azurestaticapps.net/
